### PR TITLE
Tushar case sen email bug fix

### PR DESCRIPTION
**Pull request by tusharraval102**
Fix for bug #285. Now all emails registered are automatically saved as lower case.

### CODE REVIEW

**Review by smarkandu — CHANGES_REQUESTED** [review]
You also need it to be case-insensitive for the sign-in as well.  If a user enters his email address to login, it should convert the email string entered to lowercase and then compare it with the lowercase keys for the Client collection as well.  This is for both the admin and client app.

**Comment by tusharraval102** [comment]
> You also need it to be case-insensitive for the sign-in as well. If a user enters his email address to login, it should convert the email string entered to lowercase and then compare it with the lowercase keys for the Client/Admin collection as well.

This has now been fixed.

**Review by MarwaKhalid — APPROVED** [review]
Tested both pages. 

Following inputs were tested & passed!
When signed up it stores my email as lowercase in the backend
When trying to sign in, it lets me sign in regardless of upper or lowercase
If creating an account with different uppercases, but the account already exists as lowercase. It doesnt let me create. 

So I'm approving changes.

**Review by smarkandu — APPROVED** [review]
PR looks good now: approved!

**Pull request merged**
